-- 00_setup.sql
-- Creates a small EMPLOYEES table for demos.


BEGIN
EXECUTE IMMEDIATE 'DROP TABLE employees_demo PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/


CREATE TABLE employees_demo (
employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR2(50),
last_name VARCHAR2(50),
department_id NUMBER,
base_salary NUMBER(10,2),
city VARCHAR2(64),
status VARCHAR2(20) -- e.g., ACTIVE, TERMINATED
);
